### 3. Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd

# Create a sample dataframe with a categorical variable and a target variable 
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [3]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [4]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [5]:
df['city_encoded'] = df['city'].map(mean_price)

In [6]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

### Practice Exercise:

In [9]:
import seaborn as sns
df1=sns.load_dataset('tips')

In [10]:
df1.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
df1['time']

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [13]:
time_order = df1.groupby('time')['tip'].mean().sort_values()

In [14]:
ordinal_map = {k:i for i,k in enumerate(time_order)}
ordinal_map

{2.7280882352941176: 0, 3.102670454545455: 1}

In [15]:
df1['time_encoded'] = df1['time'].map(ordinal_map)

In [16]:
df1.head()

   total_bill   tip     sex smoker  day    time  size  time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2           NaN
1       10.34  1.66    Male     No  Sun  Dinner     3           NaN
2       21.01  3.50    Male     No  Sun  Dinner     3           NaN
3       23.68  3.31    Male     No  Sun  Dinner     2           NaN
4       24.59  3.61  Female     No  Sun  Dinner     4           NaN